// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgrammingProject.Data;

#nullable disable

namespace ProgrammingProject.Migrations
{
    [DbContext(typeof(EasyWalkContext))]
    [Migration("20230328015934_NewSeedData")]
    partial class NewSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogWalkingSession", b =>
                {
                    b.Property<int>("DogListId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WalkingSessionsStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("DogListId", "WalkingSessionsStartTime");

                    b.HasIndex("WalkingSessionsStartTime");

                    b.ToTable("DogWalkingSession");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVaccinated")
                        .HasColumnType("bit");

                    b.Property<string>("MicrochipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("VetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VetId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("ProgrammingProject.Models.DogRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DogID")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalkerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DogID");

                    b.HasIndex("WalkerID");

                    b.ToTable("DogRatings");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Login", b =>
                {
                    b.Property<string>("LoginID")
                        .HasMaxLength(8)
                        .HasColumnType("char");

                    b.Property<int>("Locked")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("char");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LoginID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ProgrammingProject.Models.PlacesWalked", b =>
                {
                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalkerId")
                        .HasColumnType("int");

                    b.HasKey("Suburb");

                    b.HasIndex("WalkerId");

                    b.ToTable("PlacesWalked");
                });

            modelBuilder.Entity("ProgrammingProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgrammingProject.Models.Vet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(95)
                        .HasColumnType("nvarchar(95)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Vets");
                });

            modelBuilder.Entity("ProgrammingProject.Models.WalkerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerID")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalkerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerID");

                    b.HasIndex("WalkerID");

                    b.ToTable("WalkerRatings");
                });

            modelBuilder.Entity("ProgrammingProject.Models.WalkingSession", b =>
                {
                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WalkerID")
                        .HasColumnType("int");

                    b.HasKey("StartTime");

                    b.HasIndex("WalkerID");

                    b.ToTable("WalkingSession");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Administrator", b =>
                {
                    b.HasBaseType("ProgrammingProject.Models.User");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Owner", b =>
                {
                    b.HasBaseType("ProgrammingProject.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Walker", b =>
                {
                    b.HasBaseType("ProgrammingProject.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<bool>("IsInsured")
                        .HasColumnType("bit");

                    b.Property<string>("PhNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("User", t =>
                        {
                            t.Property("Address")
                                .HasColumnName("Walker_Address");

                            t.Property("PhNumber")
                                .HasColumnName("Walker_PhNumber");
                        });

                    b.HasDiscriminator().HasValue("Walker");
                });

            modelBuilder.Entity("DogWalkingSession", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Dog", null)
                        .WithMany()
                        .HasForeignKey("DogListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgrammingProject.Models.WalkingSession", null)
                        .WithMany()
                        .HasForeignKey("WalkingSessionsStartTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgrammingProject.Models.Dog", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Owner", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgrammingProject.Models.Vet", "Vet")
                        .WithMany("Dogs")
                        .HasForeignKey("VetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Vet");
                });

            modelBuilder.Entity("ProgrammingProject.Models.DogRating", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Dog", "Dog")
                        .WithMany("DogRatings")
                        .HasForeignKey("DogID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ProgrammingProject.Models.Walker", "Walker")
                        .WithMany("DogRatings")
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Dog");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Login", b =>
                {
                    b.HasOne("ProgrammingProject.Models.User", "User")
                        .WithOne("Login")
                        .HasForeignKey("ProgrammingProject.Models.Login", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProgrammingProject.Models.PlacesWalked", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Walker", "Walker")
                        .WithMany("PlacesWalked")
                        .HasForeignKey("WalkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("ProgrammingProject.Models.WalkerRating", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Owner", "Owner")
                        .WithMany("WalkerRatings")
                        .HasForeignKey("OwnerID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ProgrammingProject.Models.Walker", "Walker")
                        .WithMany("WalkerRatings")
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("ProgrammingProject.Models.WalkingSession", b =>
                {
                    b.HasOne("ProgrammingProject.Models.Walker", "Walker")
                        .WithMany("WalkingSessions")
                        .HasForeignKey("WalkerID")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Walker");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Dog", b =>
                {
                    b.Navigation("DogRatings");
                });

            modelBuilder.Entity("ProgrammingProject.Models.User", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();
                });

            modelBuilder.Entity("ProgrammingProject.Models.Vet", b =>
                {
                    b.Navigation("Dogs");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Owner", b =>
                {
                    b.Navigation("Dogs");

                    b.Navigation("WalkerRatings");
                });

            modelBuilder.Entity("ProgrammingProject.Models.Walker", b =>
                {
                    b.Navigation("DogRatings");

                    b.Navigation("PlacesWalked");

                    b.Navigation("WalkerRatings");

                    b.Navigation("WalkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
